---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: create group devops-group on 10.8.87.181:7990
      uri:
        url: "http://10.8.87.181:7990/rest/api/1.0/admin/groups?name=devops-group"
        method: POST
        user: admin
        password: "admin"
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        status_code: 200
      ignore_errors: True
      delegate_to: localhost
