--- 
- 
  connection: local
  gather_facts: false
  hosts: localhost
  tasks: 
    - 
      name: create devs00001 plan on 10.8.87.182:8085
      shell: /opt/atlassian-cli-7.0.0/bamboo.sh --server http://10.8.87.182:8085 --user admin --password 'admin123' --action createPlan  --plan "Dev-N00001"  --name "devs00001"  --description "This is a sample plan"

    - 
      name: create devs00001 plan on 10.8.87.182:8085
      shell: /opt/atlassian-cli-7.0.0/bamboo.sh --server http://10.8.87.182:8085 --user admin --password 'admin123' --action addRepository --plan "Dev-N00001"  --name "devs00001" --repositoryKey STASH --field1 repository.stash.projectKey --value1 DEV-N0067 --field2 repository.stash.repositoryId --value2 {{ repositoryId }} --field3 repository.stash.repositorySlug --value3 devopscicd0067 --field4 repository.stash.server --value4 7083c64a-7591-3bd4-a5ec-a9791ccb5c8d --field5 branch --value5 master --field6 repository.stash.repositoryUrl --value6 "http://admin@10.8.87.181:7990/scm/DEV-N0067/devopscicd0067.git"
